# Generated by Django 2.2.4 on 2020-05-28 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
    ]
