# Generated by Django 2.2.4 on 2020-05-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
