# Generated by Django 2.2.4 on 2020-05-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmpass',
        ),
    ]
